### ISSUE TITLE
Using classes inside groups

### ISSUE THREAD

**Issue by mike-2013** [rguezque/katya-router#2]
When using class inside group:

$katya->group('/foo', function(Group $group) {
    $user = new App\Controller\User();
    $katya->get('/', [$user, 'showProfile']);

    $group->get('/baz', function(Request $request, Response $response) {
        $response->render('welcome.php')
    });
});
Fatal error: Uncaught TypeError: rguezque\Group::get(): Argument #2 ($closure) must be of type Closure, array given

**Comment by rguezque** [comment]
Solved.
